<a href="https://colab.research.google.com/github/architawasthi99/Pandas/blob/main/06_series_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

Q-1: Write a program to create an empty series.

In [ ]:
marks=pd.Series([],dtype='float64')
print(type(marks))

<class 'pandas.core.series.Series'>


Q-2: Write a Pandas program to add, subtract, multiple and divide two Pandas Series.

In [ ]:
num1=pd.Series([22,33,44,55,66,77,88])
num2=pd.Series([22,33,44,55,66,77,88])

In [ ]:
num1+num2

0     44
1     66
2     88
3    110
4    132
5    154
6    176
dtype: int64

In [ ]:
num1-num2

0    0
1    0
2    0
3    0
4    0
5    0
6    0
dtype: int64

In [ ]:
num1*num2

0     484
1    1089
2    1936
3    3025
4    4356
5    5929
6    7744
dtype: int64

In [ ]:
num1/num2

0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
5    1.0
6    1.0
dtype: float64

Q-3 Write a Pandas program to compare the elements of the two Pandas Series.

In [ ]:
s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 10])

In [ ]:
s1==s2

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [ ]:
s1>s2

0     True
1     True
2     True
3     True
4    False
dtype: bool

In [ ]:
s1<s2

0    False
1    False
2    False
3    False
4    False
dtype: bool

Q-5.Write a function to change the data type of given a column or a Series. Function takes series and data type as input, returns the converted series.

In [ ]:
def convert(new,dtype):
  new=new.astype(dtype)
  return new

new=pd.Series([22,33,44,55,66],dtype='int64')
result=convert(new,'int16')
print(result)
print(result.dtype)

0    22
1    33
2    44
3    55
4    66
dtype: int16
int16

Q-6 Find top 10 most run getter from the series.

In [ ]:
runs=pd.read_csv('/content/batsman_runs_series.csv',index_col='batter').squeeze("columns")
runs.sort_values(ascending=False).head(10)

batter
V Kohli           6634
S Dhawan          6244
DA Warner         5883
RG Sharma         5881
SK Raina          5536
AB de Villiers    5181
CH Gayle          4997
MS Dhoni          4978
RV Uthappa        4954
KD Karthik        4377
Name: batsman_run, dtype: int64

Q-7 No of players having runs above 3000

In [ ]:
runs[runs.values>3000].size

20

Q-8 No of players having runs above mean value?

In [ ]:
runs[runs.values>runs.mean()].count()

np.int64(128)

Q-9
i. Read `items.csv` making `item_name` as index.
ii. Show no of nan values
ii. Item price is given in $, so convert it to rupees without currency symbol.
iii. Make data type of newly made series as float.
iv. Fill nan with mean of the series

In [3]:
read=pd.read_csv('/content/items.csv',index_col='item_name').squeeze("columns")
print(read.size-read.count())

50

In [4]:
read=read.str.replace('$','',regex=False).astype(float)
price_inr=read * 94
price_inr

item_name
Chips and Fresh Tomato Salsa              224.66
Izze                                      318.66
Nantucket Nectar                          318.66
Chips and Tomatillo-Green Chili Salsa     224.66
Chicken Bowl                             1596.12
                                          ...
Steak Burrito                            1104.50
Steak Burrito                            1104.50
Chicken Salad Bowl                       1057.50
Chicken Salad Bowl                        822.50
Chicken Salad Bowl                        822.50
Name: item_price, Length: 4622, dtype: float64

In [7]:
price_inr.dtype

dtype('float64')

In [10]:
mean=price_inr.mean()

print(mean)

price_inr.fillna(mean)

701.5249606299213

item_name
Chips and Fresh Tomato Salsa              224.66
Izze                                      318.66
Nantucket Nectar                          318.66
Chips and Tomatillo-Green Chili Salsa     224.66
Chicken Bowl                             1596.12
                                          ...
Steak Burrito                            1104.50
Steak Burrito                            1104.50
Chicken Salad Bowl                       1057.50
Chicken Salad Bowl                        822.50
Chicken Salad Bowl                        822.50
Name: item_price, Length: 4622, dtype: float64